// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backend1.proto

package my.sdtest.backend1;

public interface B1ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.sdtest.backend1.B1Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string answer = 1;</code>
   */
  java.lang.String getAnswer();
  /**
   * <code>string answer = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnswerBytes();
}
