// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backend1.proto

package my.sdtest.backend1;

public final class Backend1 {
  private Backend1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_sdtest_backend1_B1Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_sdtest_backend1_B1Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_sdtest_backend1_B1Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_sdtest_backend1_B1Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016backend1.proto\022\022my.sdtest.backend1\"\034\n\t" +
      "B1Request\022\017\n\007message\030\001 \001(\t\"\034\n\nB1Response" +
      "\022\016\n\006answer\030\001 \001(\t2\277\001\n\017Backend1Service\022P\n\r" +
      "HelloBackend1\022\035.my.sdtest.backend1.B1Req" +
      "uest\032\036.my.sdtest.backend1.B1Response\"\000\022Z" +
      "\n\023HelloBackend1Stream\022\035.my.sdtest.backen" +
      "d1.B1Request\032\036.my.sdtest.backend1.B1Resp" +
      "onse\"\000(\0010\001B\026\n\022my.sdtest.backend1P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_my_sdtest_backend1_B1Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_my_sdtest_backend1_B1Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_sdtest_backend1_B1Request_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_my_sdtest_backend1_B1Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_my_sdtest_backend1_B1Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_sdtest_backend1_B1Response_descriptor,
        new java.lang.String[] { "Answer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
