// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backend1.proto

package my.sdtest.backend1;

public interface B1RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.sdtest.backend1.B1Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
