version: '2'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  prometheus-b:
    build:
      context: ./prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3100:3000
    environment:
     - "GF_SERVER_DOMAIN=localhost"
     - "GF_SERVER_HTTP_PORT=3000"
     - "GF_SERVER_PROTOCOL=http"