// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backend2.proto

package my.sdtest.backend2;

public interface B2RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.sdtest.backend2.B2Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
