// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backend2.proto

package my.sdtest.backend2;

public final class Backend2 {
  private Backend2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_sdtest_backend2_B2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_sdtest_backend2_B2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_sdtest_backend2_B2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_sdtest_backend2_B2Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016backend2.proto\022\022my.sdtest.backend2\"\034\n\t" +
      "B2Request\022\017\n\007message\030\001 \001(\t\"\034\n\nB2Response" +
      "\022\016\n\006answer\030\001 \001(\t2\277\001\n\017Backend2Service\022P\n\r" +
      "HelloBackend2\022\035.my.sdtest.backend2.B2Req" +
      "uest\032\036.my.sdtest.backend2.B2Response\"\000\022Z" +
      "\n\023HelloBackend2Stream\022\035.my.sdtest.backen" +
      "d2.B2Request\032\036.my.sdtest.backend2.B2Resp" +
      "onse\"\000(\0010\001B\026\n\022my.sdtest.backend2P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_my_sdtest_backend2_B2Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_my_sdtest_backend2_B2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_sdtest_backend2_B2Request_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_my_sdtest_backend2_B2Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_my_sdtest_backend2_B2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_sdtest_backend2_B2Response_descriptor,
        new java.lang.String[] { "Answer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
