// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backend2.proto

package my.sdtest.backend2;

public interface B2ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.sdtest.backend2.B2Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string answer = 1;</code>
   */
  java.lang.String getAnswer();
  /**
   * <code>string answer = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnswerBytes();
}
